controllers:
    resource: ../src/Controller/
    type: attribute


app_homepage:
    path: /
    controller: App\Controller\HomeController::login


contact:
    path: /contact
    controller: App\Controller\ContactController::index
