controllers:
    resource: ../src/Controller/
    type: attribute


app_homepage:
    path: /
    controller: App\Controller\ProductController::categoryBrand

profile_edit:
    path: /modif_profile
    controller: App\Controller\ProfileModifController::edit

