<?php

<<<<<<<< HEAD:var/cache/dev/ContainerIyGap9Z/get_ServiceLocator_HIhw834Service.php
namespace ContainerIyGap9Z;
========
namespace ContainerXTAqN1E;

>>>>>>>> bb7cf4e46858556b526425818018d31f9181e790:var/cache/dev/ContainerXTAqN1E/get_ServiceLocator_HIhw834Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HIhw834Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HIhw834' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HIhw834'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'productRepository' => 'App\\Repository\\ProductRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
