<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJCoxZzy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJCoxZzy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJCoxZzy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJCoxZzy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJCoxZzy\App_KernelDevDebugContainer([
    'container.build_hash' => 'JCoxZzy',
    'container.build_id' => '616e0b96',
    'container.build_time' => 1715394425,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJCoxZzy');
