<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVnVjWjg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVnVjWjg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVnVjWjg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVnVjWjg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

<<<<<<< HEAD
return new \Container52qbUfV\App_KernelDevDebugContainer([
    'container.build_hash' => '52qbUfV',
    'container.build_id' => '298995fb',
    'container.build_time' => 1716276065,
], __DIR__.\DIRECTORY_SEPARATOR.'Container52qbUfV');
=======
return new \ContainerVnVjWjg\App_KernelDevDebugContainer([
    'container.build_hash' => 'VnVjWjg',
    'container.build_id' => 'e0341cfb',
    'container.build_time' => 1716211956,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVnVjWjg');
>>>>>>> 7f4b3e24db29171d18e8f41225fe2646cb5b87cf
