<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPD9Msux\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPD9Msux/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPD9Msux.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPD9Msux\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPD9Msux\App_KernelDevDebugContainer([
    'container.build_hash' => 'PD9Msux',
    'container.build_id' => 'ae132c1d',
    'container.build_time' => 1716298007,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPD9Msux');
